frog_lives=3;
frog_score=0;
egg_captured=false;
game_over=false;
sound_over_has_been_played=true;
draw_set_font(font_lives_and_score)
audio_play_sound(sound_rushing_water,0,true);
audio_play_sound(sound_traffic,0,true);
audio_play_sound(sound_game_music,0,true);